version: '3.8'

services:
  # ĐỔI TÊN SERVICE CHO KHỚP VỚI CHUỖI KẾT NỐI
  hus_bakery_db: 
    image: mysql:8.0
    container_name: bakery_mysql
    restart: always
    environment:
      # SỬA CHO KHỚP VỚI DB_URI CỦA BẠN
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hus_bakery
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - bakery-network

  bakery_backend:
    build: ./backend
    container_name: bakery_backend
    restart: always
    environment:
      # Truyền trực tiếp biến này vào cho Flask
      DB_URI: "mysql+pymysql://root:root@hus_bakery_db:3306/hus_bakery"
      SECRET_KEY: "nguyenbaothach"
      JWT_SECRET_KEY: "hus_bakery_backend"
      MAIL_USERNAME: "thachnb.mathtech@gmail.com"
      MAIL_PASSWORD: "rpiziafljmspbwkc"
    depends_on:
      hus_bakery_db:
        condition: service_healthy
    networks:
      - bakery-network

  bakery_frontend_user:
    build:
      context: ./frontend-user
      args:
        - VITE_API_URL=https://husbakery.duckdns.org/api
    container_name: bakery_frontend_user
    networks:
      - bakery-network

  bakery_frontend_admin:
    build:
      context: ./frontend-admin
      args:
        - VITE_API_URL=https://husbakery.duckdns.org/api
    container_name: bakery_frontend_admin
    networks:
      - bakery-network

  bakery_gateway:
    image: nginx:alpine
    container_name: bakery_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_gateway.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - bakery_frontend_user
      - bakery_frontend_admin
      - bakery_backend
    networks:
      - bakery-network

volumes:
  mysql_data:

networks:
  bakery-network:
    driver: bridge