server {
    listen 80;
    server_name husbakery.duckdns.org;
    return 301 https://$host$request_uri; # Chuyển hướng sang HTTPS
}

server {
    listen 443 ssl;
    server_name husbakery.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/husbakery.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/husbakery.duckdns.org/privkey.pem;

    location /api {
        proxy_pass http://bakery_backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /admin {
        proxy_pass http://bakery_frontend_admin:80;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://bakery_frontend_user:80;
        proxy_set_header Host $host;
    }
}